-- phpMyAdmin SQL Dump
-- version 4.9.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 15 дек 2019 в 23:06
-- Версия на сървъра: 10.4.8-MariaDB
-- PHP Version: 7.3.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `imagesdatabase`
--

-- --------------------------------------------------------

--
-- Структура на таблица `photos`
--

CREATE TABLE `photos` (
  `id` int(11) NOT NULL,
  `file_name` varchar(255) COLLATE utf8_bin NOT NULL,
  `user_name` varchar(100) COLLATE utf8_bin NOT NULL,
  `uploaded_on` datetime NOT NULL,
  `status` enum('1','0') COLLATE utf8_bin NOT NULL DEFAULT '1',
  `text` mediumtext COLLATE utf8_bin NOT NULL,
  `album` varchar(100) COLLATE utf8_bin NOT NULL,
  `likesUsers` mediumtext COLLATE utf8_bin NOT NULL,
  `dislikesUsers` mediumtext COLLATE utf8_bin NOT NULL,
  `likesCount` int(11) NOT NULL DEFAULT 0,
  `dislikesCount` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Схема на данните от таблица `photos`
--

INSERT INTO `photos` (`id`, `file_name`, `user_name`, `uploaded_on`, `status`, `text`, `album`, `likesUsers`, `dislikesUsers`, `likesCount`, `dislikesCount`) VALUES
(139, '2018_02_01_39875_1517462499._large.jpg', 'Bogdan', '2019-07-05 22:50:14', '1', 'Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species especially fish and turtles. In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean. Most recently, Bali was the host of the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site. It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation.', 'Bali', '', '', 0, 0),
(140, '6504_16041513160041537347.jpg', 'Bogdan', '2019-07-05 22:50:14', '1', 'Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species especially fish and turtles. In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean. Most recently, Bali was the host of the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site. It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation.', 'Bali', '', '', 0, 0),
(141, '107387387.jpg', 'Bogdan', '2019-07-05 22:50:14', '1', 'Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species especially fish and turtles. In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean. Most recently, Bali was the host of the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site. It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation.', 'Bali', '', '', 0, 0),
(142, '109064489.jpg', 'Bogdan', '2019-07-05 22:50:14', '1', 'Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species especially fish and turtles. In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean. Most recently, Bali was the host of the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site. It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation.', 'Bali', '', '', 0, 0),
(143, 'Bali3.jpg', 'Bogdan', '2019-07-05 22:50:14', '1', 'Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species especially fish and turtles. In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean. Most recently, Bali was the host of the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site. It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation.', 'Bali', '', '', 0, 0),
(144, '190130_Dane-Canada-launches-new-immigration-program-for-northern-and-rural-communities-new.png', 'Bogdan', '2019-07-05 22:50:59', '1', 'Despite Canada’s great size, it is one of the world’s most sparsely populated countries. This fact, coupled with the grandeur of the landscape, has been central to the sense of Canadian national identity, as expressed by the Dublin-born writer Anna Brownell Jameson, who explored central Ontario in 1837 and remarked exultantly on “the seemingly interminable line of trees before you; the boundless wilderness around you; the mysterious depths amid the multitudinous foliage, where foot of man hath never penetrated…the solitude in which we proceeded mile after mile, no human being, no human dwelling within sight.” Although Canadians are comparatively few in number, however, they have crafted what many observers consider to be a model multicultural society, welcoming immigrant populations from every other continent. In addition, Canada harbours and exports a wealth of natural resources and intellectual capital equaled by few other countries. Canada is officially bilingual in English and French, reflecting the country’s history as ground once contested by two of Europe’s great powers. The word Canada is derived from the Huron-Iroquois kanata, meaning a village or settlement. In the 16th century, French explorer Jacques Cartier used the name Canada to refer to the area around the settlement that is now Quebec City. Later, Canada was used as a synonym for New France, which, from 1534 to 1763, included all the French possessions along the St. Lawrence River and the Great Lakes. After the British conquest of New France, the name Quebec was sometimes used instead of Canada. The name Canada was fully restored after 1791, when Britain divided old Quebec into the provinces of Upper and Lower Canada (renamed in 1841 Canada West and Canada East, respectively, and collectively called Canada). In 1867 the British North America Act created a confederation from three colonies (Nova Scotia, New Brunswick, and Canada) called the Dominion of Canada. The act also divided the old colony of Canada into the separate provinces of Ontario and Quebec. Dominion status allowed Canada a large measure of self-rule, but matters pertaining to international diplomacy and military alliances were reserved to the British crown. Canada became entirely self-governing within the British Empire in 1931, though full legislative independence was not achieved until 1982, when Canada obtained the right to amend its own constitution.', 'Canada', '', '', 0, 0),
(145, '348761.jpg', 'Bogdan', '2019-07-05 22:50:59', '1', 'Despite Canada’s great size, it is one of the world’s most sparsely populated countries. This fact, coupled with the grandeur of the landscape, has been central to the sense of Canadian national identity, as expressed by the Dublin-born writer Anna Brownell Jameson, who explored central Ontario in 1837 and remarked exultantly on “the seemingly interminable line of trees before you; the boundless wilderness around you; the mysterious depths amid the multitudinous foliage, where foot of man hath never penetrated…the solitude in which we proceeded mile after mile, no human being, no human dwelling within sight.” Although Canadians are comparatively few in number, however, they have crafted what many observers consider to be a model multicultural society, welcoming immigrant populations from every other continent. In addition, Canada harbours and exports a wealth of natural resources and intellectual capital equaled by few other countries. Canada is officially bilingual in English and French, reflecting the country’s history as ground once contested by two of Europe’s great powers. The word Canada is derived from the Huron-Iroquois kanata, meaning a village or settlement. In the 16th century, French explorer Jacques Cartier used the name Canada to refer to the area around the settlement that is now Quebec City. Later, Canada was used as a synonym for New France, which, from 1534 to 1763, included all the French possessions along the St. Lawrence River and the Great Lakes. After the British conquest of New France, the name Quebec was sometimes used instead of Canada. The name Canada was fully restored after 1791, when Britain divided old Quebec into the provinces of Upper and Lower Canada (renamed in 1841 Canada West and Canada East, respectively, and collectively called Canada). In 1867 the British North America Act created a confederation from three colonies (Nova Scotia, New Brunswick, and Canada) called the Dominion of Canada. The act also divided the old colony of Canada into the separate provinces of Ontario and Quebec. Dominion status allowed Canada a large measure of self-rule, but matters pertaining to international diplomacy and military alliances were reserved to the British crown. Canada became entirely self-governing within the British Empire in 1931, though full legislative independence was not achieved until 1982, when Canada obtained the right to amend its own constitution.', 'Canada', '', '', 0, 0),
(146, 'Canada Background 4 19 bg.jpg', 'Bogdan', '2019-07-05 22:50:59', '1', 'Despite Canada’s great size, it is one of the world’s most sparsely populated countries. This fact, coupled with the grandeur of the landscape, has been central to the sense of Canadian national identity, as expressed by the Dublin-born writer Anna Brownell Jameson, who explored central Ontario in 1837 and remarked exultantly on “the seemingly interminable line of trees before you; the boundless wilderness around you; the mysterious depths amid the multitudinous foliage, where foot of man hath never penetrated…the solitude in which we proceeded mile after mile, no human being, no human dwelling within sight.” Although Canadians are comparatively few in number, however, they have crafted what many observers consider to be a model multicultural society, welcoming immigrant populations from every other continent. In addition, Canada harbours and exports a wealth of natural resources and intellectual capital equaled by few other countries. Canada is officially bilingual in English and French, reflecting the country’s history as ground once contested by two of Europe’s great powers. The word Canada is derived from the Huron-Iroquois kanata, meaning a village or settlement. In the 16th century, French explorer Jacques Cartier used the name Canada to refer to the area around the settlement that is now Quebec City. Later, Canada was used as a synonym for New France, which, from 1534 to 1763, included all the French possessions along the St. Lawrence River and the Great Lakes. After the British conquest of New France, the name Quebec was sometimes used instead of Canada. The name Canada was fully restored after 1791, when Britain divided old Quebec into the provinces of Upper and Lower Canada (renamed in 1841 Canada West and Canada East, respectively, and collectively called Canada). In 1867 the British North America Act created a confederation from three colonies (Nova Scotia, New Brunswick, and Canada) called the Dominion of Canada. The act also divided the old colony of Canada into the separate provinces of Ontario and Quebec. Dominion status allowed Canada a large measure of self-rule, but matters pertaining to international diplomacy and military alliances were reserved to the British crown. Canada became entirely self-governing within the British Empire in 1931, though full legislative independence was not achieved until 1982, when Canada obtained the right to amend its own constitution.', 'Canada', '', '', 0, 0),
(147, 'canada-33723235-1468496086-ImageGalleryLightboxLarge.jpg', 'Bogdan', '2019-07-05 22:50:59', '1', 'Despite Canada’s great size, it is one of the world’s most sparsely populated countries. This fact, coupled with the grandeur of the landscape, has been central to the sense of Canadian national identity, as expressed by the Dublin-born writer Anna Brownell Jameson, who explored central Ontario in 1837 and remarked exultantly on “the seemingly interminable line of trees before you; the boundless wilderness around you; the mysterious depths amid the multitudinous foliage, where foot of man hath never penetrated…the solitude in which we proceeded mile after mile, no human being, no human dwelling within sight.” Although Canadians are comparatively few in number, however, they have crafted what many observers consider to be a model multicultural society, welcoming immigrant populations from every other continent. In addition, Canada harbours and exports a wealth of natural resources and intellectual capital equaled by few other countries. Canada is officially bilingual in English and French, reflecting the country’s history as ground once contested by two of Europe’s great powers. The word Canada is derived from the Huron-Iroquois kanata, meaning a village or settlement. In the 16th century, French explorer Jacques Cartier used the name Canada to refer to the area around the settlement that is now Quebec City. Later, Canada was used as a synonym for New France, which, from 1534 to 1763, included all the French possessions along the St. Lawrence River and the Great Lakes. After the British conquest of New France, the name Quebec was sometimes used instead of Canada. The name Canada was fully restored after 1791, when Britain divided old Quebec into the provinces of Upper and Lower Canada (renamed in 1841 Canada West and Canada East, respectively, and collectively called Canada). In 1867 the British North America Act created a confederation from three colonies (Nova Scotia, New Brunswick, and Canada) called the Dominion of Canada. The act also divided the old colony of Canada into the separate provinces of Ontario and Quebec. Dominion status allowed Canada a large measure of self-rule, but matters pertaining to international diplomacy and military alliances were reserved to the British crown. Canada became entirely self-governing within the British Empire in 1931, though full legislative independence was not achieved until 1982, when Canada obtained the right to amend its own constitution.', 'Canada', '', '', 0, 0),
(148, 'canada-ranks-top.jpg', 'Bogdan', '2019-07-05 22:50:59', '1', 'Despite Canada’s great size, it is one of the world’s most sparsely populated countries. This fact, coupled with the grandeur of the landscape, has been central to the sense of Canadian national identity, as expressed by the Dublin-born writer Anna Brownell Jameson, who explored central Ontario in 1837 and remarked exultantly on “the seemingly interminable line of trees before you; the boundless wilderness around you; the mysterious depths amid the multitudinous foliage, where foot of man hath never penetrated…the solitude in which we proceeded mile after mile, no human being, no human dwelling within sight.” Although Canadians are comparatively few in number, however, they have crafted what many observers consider to be a model multicultural society, welcoming immigrant populations from every other continent. In addition, Canada harbours and exports a wealth of natural resources and intellectual capital equaled by few other countries. Canada is officially bilingual in English and French, reflecting the country’s history as ground once contested by two of Europe’s great powers. The word Canada is derived from the Huron-Iroquois kanata, meaning a village or settlement. In the 16th century, French explorer Jacques Cartier used the name Canada to refer to the area around the settlement that is now Quebec City. Later, Canada was used as a synonym for New France, which, from 1534 to 1763, included all the French possessions along the St. Lawrence River and the Great Lakes. After the British conquest of New France, the name Quebec was sometimes used instead of Canada. The name Canada was fully restored after 1791, when Britain divided old Quebec into the provinces of Upper and Lower Canada (renamed in 1841 Canada West and Canada East, respectively, and collectively called Canada). In 1867 the British North America Act created a confederation from three colonies (Nova Scotia, New Brunswick, and Canada) called the Dominion of Canada. The act also divided the old colony of Canada into the separate provinces of Ontario and Quebec. Dominion status allowed Canada a large measure of self-rule, but matters pertaining to international diplomacy and military alliances were reserved to the British crown. Canada became entirely self-governing within the British Empire in 1931, though full legislative independence was not achieved until 1982, when Canada obtained the right to amend its own constitution.', 'Canada', '', '', 0, 0),
(149, 'moving-to-canada-drivers-licence.jpg', 'Bogdan', '2019-07-05 22:50:59', '1', 'Despite Canada’s great size, it is one of the world’s most sparsely populated countries. This fact, coupled with the grandeur of the landscape, has been central to the sense of Canadian national identity, as expressed by the Dublin-born writer Anna Brownell Jameson, who explored central Ontario in 1837 and remarked exultantly on “the seemingly interminable line of trees before you; the boundless wilderness around you; the mysterious depths amid the multitudinous foliage, where foot of man hath never penetrated…the solitude in which we proceeded mile after mile, no human being, no human dwelling within sight.” Although Canadians are comparatively few in number, however, they have crafted what many observers consider to be a model multicultural society, welcoming immigrant populations from every other continent. In addition, Canada harbours and exports a wealth of natural resources and intellectual capital equaled by few other countries. Canada is officially bilingual in English and French, reflecting the country’s history as ground once contested by two of Europe’s great powers. The word Canada is derived from the Huron-Iroquois kanata, meaning a village or settlement. In the 16th century, French explorer Jacques Cartier used the name Canada to refer to the area around the settlement that is now Quebec City. Later, Canada was used as a synonym for New France, which, from 1534 to 1763, included all the French possessions along the St. Lawrence River and the Great Lakes. After the British conquest of New France, the name Quebec was sometimes used instead of Canada. The name Canada was fully restored after 1791, when Britain divided old Quebec into the provinces of Upper and Lower Canada (renamed in 1841 Canada West and Canada East, respectively, and collectively called Canada). In 1867 the British North America Act created a confederation from three colonies (Nova Scotia, New Brunswick, and Canada) called the Dominion of Canada. The act also divided the old colony of Canada into the separate provinces of Ontario and Quebec. Dominion status allowed Canada a large measure of self-rule, but matters pertaining to international diplomacy and military alliances were reserved to the British crown. Canada became entirely self-governing within the British Empire in 1931, though full legislative independence was not achieved until 1982, when Canada obtained the right to amend its own constitution.', 'Canada', '', '', 0, 0),
(150, 'otentik-870.jpg', 'Bogdan', '2019-07-05 22:50:59', '1', 'Despite Canada’s great size, it is one of the world’s most sparsely populated countries. This fact, coupled with the grandeur of the landscape, has been central to the sense of Canadian national identity, as expressed by the Dublin-born writer Anna Brownell Jameson, who explored central Ontario in 1837 and remarked exultantly on “the seemingly interminable line of trees before you; the boundless wilderness around you; the mysterious depths amid the multitudinous foliage, where foot of man hath never penetrated…the solitude in which we proceeded mile after mile, no human being, no human dwelling within sight.” Although Canadians are comparatively few in number, however, they have crafted what many observers consider to be a model multicultural society, welcoming immigrant populations from every other continent. In addition, Canada harbours and exports a wealth of natural resources and intellectual capital equaled by few other countries. Canada is officially bilingual in English and French, reflecting the country’s history as ground once contested by two of Europe’s great powers. The word Canada is derived from the Huron-Iroquois kanata, meaning a village or settlement. In the 16th century, French explorer Jacques Cartier used the name Canada to refer to the area around the settlement that is now Quebec City. Later, Canada was used as a synonym for New France, which, from 1534 to 1763, included all the French possessions along the St. Lawrence River and the Great Lakes. After the British conquest of New France, the name Quebec was sometimes used instead of Canada. The name Canada was fully restored after 1791, when Britain divided old Quebec into the provinces of Upper and Lower Canada (renamed in 1841 Canada West and Canada East, respectively, and collectively called Canada). In 1867 the British North America Act created a confederation from three colonies (Nova Scotia, New Brunswick, and Canada) called the Dominion of Canada. The act also divided the old colony of Canada into the separate provinces of Ontario and Quebec. Dominion status allowed Canada a large measure of self-rule, but matters pertaining to international diplomacy and military alliances were reserved to the British crown. Canada became entirely self-governing within the British Empire in 1931, though full legislative independence was not achieved until 1982, when Canada obtained the right to amend its own constitution.', 'Canada', '', '', 0, 0),
(151, '1400AD-header_hawaii_1-original.jpg', 'Pesho', '2019-07-05 22:52:05', '1', 'Hawaii is the 8th-smallest geographically and the 11th-least populous, but the 13th-most densely populated of the 50 states. It is the only state with an Asian American plurality. Hawaii has over 1.4 million permanent residents, along with many visitors and U.S. military personnel. The state capital and largest city is Honolulu on the island of Oahu. The state ocean coastline is about 750 miles long, the fourth longest in the U.S., after the coastlines of Alaska, Florida, and California. Hawaii is the most recent state to join the union, on August 21, 1959. Hawaii is represented in the United States Congress by two senators and two representatives. As of 2019, all four seats are held by Democrats. Former representative Ed Case was elected in 2018 to the 1st congressional district. Tulsi Gabbard represents the 2nd congressional district, representing the rest of the state, which is largely rural and semi-rural. Tourism is an important part of the Hawaiian economy. Due to the mild year-round weather, tourist travel is popular throughout the year. The major holidays are the most popular times for outsiders to visit, especially in the winter months. ', 'Hawaii', '', '', 0, 0),
(152, 'best-hikes-on-kauai-hawaii-04886.jpg.optimal.jpg', 'Pesho', '2019-07-05 22:52:05', '1', 'Hawaii is the 8th-smallest geographically and the 11th-least populous, but the 13th-most densely populated of the 50 states. It is the only state with an Asian American plurality. Hawaii has over 1.4 million permanent residents, along with many visitors and U.S. military personnel. The state capital and largest city is Honolulu on the island of Oahu. The state ocean coastline is about 750 miles long, the fourth longest in the U.S., after the coastlines of Alaska, Florida, and California. Hawaii is the most recent state to join the union, on August 21, 1959. Hawaii is represented in the United States Congress by two senators and two representatives. As of 2019, all four seats are held by Democrats. Former representative Ed Case was elected in 2018 to the 1st congressional district. Tulsi Gabbard represents the 2nd congressional district, representing the rest of the state, which is largely rural and semi-rural. Tourism is an important part of the Hawaiian economy. Due to the mild year-round weather, tourist travel is popular throughout the year. The major holidays are the most popular times for outsiders to visit, especially in the winter months. ', 'Hawaii', '', '', 0, 0),
(153, 'Hawaii-1200x853.jpg', 'Pesho', '2019-07-05 22:52:05', '1', 'Hawaii is the 8th-smallest geographically and the 11th-least populous, but the 13th-most densely populated of the 50 states. It is the only state with an Asian American plurality. Hawaii has over 1.4 million permanent residents, along with many visitors and U.S. military personnel. The state capital and largest city is Honolulu on the island of Oahu. The state ocean coastline is about 750 miles long, the fourth longest in the U.S., after the coastlines of Alaska, Florida, and California. Hawaii is the most recent state to join the union, on August 21, 1959. Hawaii is represented in the United States Congress by two senators and two representatives. As of 2019, all four seats are held by Democrats. Former representative Ed Case was elected in 2018 to the 1st congressional district. Tulsi Gabbard represents the 2nd congressional district, representing the rest of the state, which is largely rural and semi-rural. Tourism is an important part of the Hawaiian economy. Due to the mild year-round weather, tourist travel is popular throughout the year. The major holidays are the most popular times for outsiders to visit, especially in the winter months. ', 'Hawaii', '', '', 0, 0),
(154, 'Judge-blocks-Hawaiis-bid-to-subpoena-Airbnb-hosts-records.jpg', 'Pesho', '2019-07-05 22:52:05', '1', 'Hawaii is the 8th-smallest geographically and the 11th-least populous, but the 13th-most densely populated of the 50 states. It is the only state with an Asian American plurality. Hawaii has over 1.4 million permanent residents, along with many visitors and U.S. military personnel. The state capital and largest city is Honolulu on the island of Oahu. The state ocean coastline is about 750 miles long, the fourth longest in the U.S., after the coastlines of Alaska, Florida, and California. Hawaii is the most recent state to join the union, on August 21, 1959. Hawaii is represented in the United States Congress by two senators and two representatives. As of 2019, all four seats are held by Democrats. Former representative Ed Case was elected in 2018 to the 1st congressional district. Tulsi Gabbard represents the 2nd congressional district, representing the rest of the state, which is largely rural and semi-rural. Tourism is an important part of the Hawaiian economy. Due to the mild year-round weather, tourist travel is popular throughout the year. The major holidays are the most popular times for outsiders to visit, especially in the winter months. ', 'Hawaii', '', '', 0, 0),
(155, '5af5b3dc5e48ec4f008b4571-750-562.jpg', 'Pesho', '2019-07-05 22:52:43', '1', 'Iceland is a Nordic island country in the North Atlantic, with a population of 360,390 and an area of 103,000 km2 (40,000 sq mi), making it the most sparsely populated country in Europe. The capital and largest city is Reykjavík, with Reykjavík and the surrounding areas in the southwest of the country being home to over two-thirds of the population. Iceland is volcanically and geologically active. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude almost entirely outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, with most of the archipelago having a tundra climate.', 'Iceland', '', '', 0, 0),
(156, 'dsc8169-res-min.jpg', 'Pesho', '2019-07-05 22:52:43', '1', 'Iceland is a Nordic island country in the North Atlantic, with a population of 360,390 and an area of 103,000 km2 (40,000 sq mi), making it the most sparsely populated country in Europe. The capital and largest city is Reykjavík, with Reykjavík and the surrounding areas in the southwest of the country being home to over two-thirds of the population. Iceland is volcanically and geologically active. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude almost entirely outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, with most of the archipelago having a tundra climate.', 'Iceland', '', '', 0, 0),
(157, 'iceland.jpg', 'Pesho', '2019-07-05 22:52:43', '1', 'Iceland is a Nordic island country in the North Atlantic, with a population of 360,390 and an area of 103,000 km2 (40,000 sq mi), making it the most sparsely populated country in Europe. The capital and largest city is Reykjavík, with Reykjavík and the surrounding areas in the southwest of the country being home to over two-thirds of the population. Iceland is volcanically and geologically active. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude almost entirely outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, with most of the archipelago having a tundra climate.', 'Iceland', '', '', 0, 0),
(158, 'lyndzii-reykjavik-2.jpg', 'Pesho', '2019-07-05 22:52:43', '1', 'Iceland is a Nordic island country in the North Atlantic, with a population of 360,390 and an area of 103,000 km2 (40,000 sq mi), making it the most sparsely populated country in Europe. The capital and largest city is Reykjavík, with Reykjavík and the surrounding areas in the southwest of the country being home to over two-thirds of the population. Iceland is volcanically and geologically active. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude almost entirely outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, with most of the archipelago having a tundra climate.', 'Iceland', '', '', 0, 0),
(159, 'pr-6-aug-2020-akureyri-iceland.jpg', 'Pesho', '2019-07-05 22:52:43', '1', 'Iceland is a Nordic island country in the North Atlantic, with a population of 360,390 and an area of 103,000 km2 (40,000 sq mi), making it the most sparsely populated country in Europe. The capital and largest city is Reykjavík, with Reykjavík and the surrounding areas in the southwest of the country being home to over two-thirds of the population. Iceland is volcanically and geologically active. The interior consists of a plateau characterised by sand and lava fields, mountains, and glaciers, and many glacial rivers flow to the sea through the lowlands. Iceland is warmed by the Gulf Stream and has a temperate climate, despite a high latitude almost entirely outside the Arctic Circle. Its high latitude and marine influence keep summers chilly, with most of the archipelago having a tundra climate.', 'Iceland', '', '', 0, 0),
(160, '640-420-avstraliia-obiavi-okeana-za-zashtitena-zona.jpg', 'Pesho', '2019-07-05 22:58:13', '1', 'Until the early 19th century, Australia was best known as \"New Holland\", a name first applied by the Dutch explorer Abel Tasman in 1644 (as Nieuw-Holland) and subsequently anglicised. Terra Australis still saw occasional usage, such as in scientific texts. The name Australia was popularised by the explorer Matthew Flinders, who said it was \"more agreeable to the ear, and an assimilation to the names of the other great portions of the earth\". Several famous early cartographers also made use of the word Australia on maps. Gerard Mercator (1512–1594) used the phrase climata australia on his double cordiform map of the world of 1538, as did Gemma Frisius (1508–1555. Australia appears in a book on astronomy by Cyriaco Jacob zum Barth published in Frankfurt-am-Main in 1545.', 'Australia', 'Bogdanbobcho_97', '', 2, 0),
(161, '768x432.jpg', 'Pesho', '2019-07-05 22:58:13', '1', 'Until the early 19th century, Australia was best known as \"New Holland\", a name first applied by the Dutch explorer Abel Tasman in 1644 (as Nieuw-Holland) and subsequently anglicised. Terra Australis still saw occasional usage, such as in scientific texts. The name Australia was popularised by the explorer Matthew Flinders, who said it was \"more agreeable to the ear, and an assimilation to the names of the other great portions of the earth\". Several famous early cartographers also made use of the word Australia on maps. Gerard Mercator (1512–1594) used the phrase climata australia on his double cordiform map of the world of 1538, as did Gemma Frisius (1508–1555. Australia appears in a book on astronomy by Cyriaco Jacob zum Barth published in Frankfurt-am-Main in 1545.', 'Australia', 'Bogdanbobcho_97', '', 2, 0),
(162, '1024-768-avstraliia.jpg', 'Pesho', '2019-07-05 22:58:13', '1', 'Until the early 19th century, Australia was best known as \"New Holland\", a name first applied by the Dutch explorer Abel Tasman in 1644 (as Nieuw-Holland) and subsequently anglicised. Terra Australis still saw occasional usage, such as in scientific texts. The name Australia was popularised by the explorer Matthew Flinders, who said it was \"more agreeable to the ear, and an assimilation to the names of the other great portions of the earth\". Several famous early cartographers also made use of the word Australia on maps. Gerard Mercator (1512–1594) used the phrase climata australia on his double cordiform map of the world of 1538, as did Gemma Frisius (1508–1555. Australia appears in a book on astronomy by Cyriaco Jacob zum Barth published in Frankfurt-am-Main in 1545.', 'Australia', 'Bogdanbobcho_97', '', 2, 0),
(163, '16699322_303.jpg', 'Pesho', '2019-07-05 22:58:13', '1', 'Until the early 19th century, Australia was best known as \"New Holland\", a name first applied by the Dutch explorer Abel Tasman in 1644 (as Nieuw-Holland) and subsequently anglicised. Terra Australis still saw occasional usage, such as in scientific texts. The name Australia was popularised by the explorer Matthew Flinders, who said it was \"more agreeable to the ear, and an assimilation to the names of the other great portions of the earth\". Several famous early cartographers also made use of the word Australia on maps. Gerard Mercator (1512–1594) used the phrase climata australia on his double cordiform map of the world of 1538, as did Gemma Frisius (1508–1555. Australia appears in a book on astronomy by Cyriaco Jacob zum Barth published in Frankfurt-am-Main in 1545.', 'Australia', 'Bogdanbobcho_97', '', 2, 0),
(164, 'Ayers-Rock-Australia.jpg', 'Pesho', '2019-07-05 22:58:13', '1', 'Until the early 19th century, Australia was best known as \"New Holland\", a name first applied by the Dutch explorer Abel Tasman in 1644 (as Nieuw-Holland) and subsequently anglicised. Terra Australis still saw occasional usage, such as in scientific texts. The name Australia was popularised by the explorer Matthew Flinders, who said it was \"more agreeable to the ear, and an assimilation to the names of the other great portions of the earth\". Several famous early cartographers also made use of the word Australia on maps. Gerard Mercator (1512–1594) used the phrase climata australia on his double cordiform map of the world of 1538, as did Gemma Frisius (1508–1555. Australia appears in a book on astronomy by Cyriaco Jacob zum Barth published in Frankfurt-am-Main in 1545.', 'Australia', 'Bogdanbobcho_97', '', 2, 0),
(165, 'fe2790ec5653a29371fa79cc865bedcf_680x_02.jpg', 'Pesho', '2019-07-05 22:58:13', '1', 'Until the early 19th century, Australia was best known as \"New Holland\", a name first applied by the Dutch explorer Abel Tasman in 1644 (as Nieuw-Holland) and subsequently anglicised. Terra Australis still saw occasional usage, such as in scientific texts. The name Australia was popularised by the explorer Matthew Flinders, who said it was \"more agreeable to the ear, and an assimilation to the names of the other great portions of the earth\". Several famous early cartographers also made use of the word Australia on maps. Gerard Mercator (1512–1594) used the phrase climata australia on his double cordiform map of the world of 1538, as did Gemma Frisius (1508–1555. Australia appears in a book on astronomy by Cyriaco Jacob zum Barth published in Frankfurt-am-Main in 1545.', 'Australia', 'Bogdanbobcho_97', '', 2, 0),
(166, 'resize_on_the_fly.jpg', 'Pesho', '2019-07-05 22:58:13', '1', 'Until the early 19th century, Australia was best known as \"New Holland\", a name first applied by the Dutch explorer Abel Tasman in 1644 (as Nieuw-Holland) and subsequently anglicised. Terra Australis still saw occasional usage, such as in scientific texts. The name Australia was popularised by the explorer Matthew Flinders, who said it was \"more agreeable to the ear, and an assimilation to the names of the other great portions of the earth\". Several famous early cartographers also made use of the word Australia on maps. Gerard Mercator (1512–1594) used the phrase climata australia on his double cordiform map of the world of 1538, as did Gemma Frisius (1508–1555. Australia appears in a book on astronomy by Cyriaco Jacob zum Barth published in Frankfurt-am-Main in 1545.', 'Australia', 'Bogdanbobcho_97', '', 2, 0),
(167, '5c3e552710f0d00a9430668b-750-563.jpg', 'Pesho', '2019-07-05 22:59:42', '1', 'The Maldives archipelago is located on the Chagos-Laccadive Ridge, a vast submarine mountain range in the Indian Ocean, which also forms a terrestrial ecoregion, together with the Chagos Archipelago and Lakshadweep. Due to the consequent risks posed by rising sea levels, the government pledged in 2009 to make the Maldives a carbon-neutral country by 2019. The Maldives is a founding member of the South Asian Association for Regional Cooperation (SAARC). It is also a member of the United Nations, the Organization of Islamic Cooperation, and the Non-Aligned Movement. The World Bank classifies the Maldives as having an upper middle-income economy. Fishing has historically been the dominant economic activity, and remains the largest sector by far, followed by the rapidly growing tourism industry. Maldives is rated \"high\" on the Human Development Index, with its per capita income significantly higher than other SAARC nations. Visitors to the Maldives do not need to apply for a visa pre-arrival, regardless of their country of origin, provided they have a valid passport, proof of onward travel, and the money to be self-sufficient while in the country. Most visitors arrive at Malé International Airport, on Hulhulé Island, adjacent to the capital Malé. The airport is served by flights to and from India, Sri Lanka, Doha, Dubai, Singapore, Istanbul, and major airports in South-East Asia, as well as charters from Europe. Gan Airport, on the southern atoll of Addu, also serves an international flight to Milan several times a week. British Airways offers direct flights to the Maldives around 2–3 times per week. The country currently has six heritage Maldivian coral mosques, all of which are listed as UNESCO tentative sites.', 'Maldives', 'Pesho', '', 1, 0),
(168, '360-underwater-superJumbo.jpg', 'Pesho', '2019-07-05 22:59:42', '1', 'The Maldives archipelago is located on the Chagos-Laccadive Ridge, a vast submarine mountain range in the Indian Ocean, which also forms a terrestrial ecoregion, together with the Chagos Archipelago and Lakshadweep. Due to the consequent risks posed by rising sea levels, the government pledged in 2009 to make the Maldives a carbon-neutral country by 2019. The Maldives is a founding member of the South Asian Association for Regional Cooperation (SAARC). It is also a member of the United Nations, the Organization of Islamic Cooperation, and the Non-Aligned Movement. The World Bank classifies the Maldives as having an upper middle-income economy. Fishing has historically been the dominant economic activity, and remains the largest sector by far, followed by the rapidly growing tourism industry. Maldives is rated \"high\" on the Human Development Index, with its per capita income significantly higher than other SAARC nations. Visitors to the Maldives do not need to apply for a visa pre-arrival, regardless of their country of origin, provided they have a valid passport, proof of onward travel, and the money to be self-sufficient while in the country. Most visitors arrive at Malé International Airport, on Hulhulé Island, adjacent to the capital Malé. The airport is served by flights to and from India, Sri Lanka, Doha, Dubai, Singapore, Istanbul, and major airports in South-East Asia, as well as charters from Europe. Gan Airport, on the southern atoll of Addu, also serves an international flight to Milan several times a week. British Airways offers direct flights to the Maldives around 2–3 times per week. The country currently has six heritage Maldivian coral mosques, all of which are listed as UNESCO tentative sites.', 'Maldives', 'Pesho', '', 1, 0),
(169, '1198107_17091019130056193074.jpg', 'Pesho', '2019-07-05 22:59:42', '1', 'The Maldives archipelago is located on the Chagos-Laccadive Ridge, a vast submarine mountain range in the Indian Ocean, which also forms a terrestrial ecoregion, together with the Chagos Archipelago and Lakshadweep. Due to the consequent risks posed by rising sea levels, the government pledged in 2009 to make the Maldives a carbon-neutral country by 2019. The Maldives is a founding member of the South Asian Association for Regional Cooperation (SAARC). It is also a member of the United Nations, the Organization of Islamic Cooperation, and the Non-Aligned Movement. The World Bank classifies the Maldives as having an upper middle-income economy. Fishing has historically been the dominant economic activity, and remains the largest sector by far, followed by the rapidly growing tourism industry. Maldives is rated \"high\" on the Human Development Index, with its per capita income significantly higher than other SAARC nations. Visitors to the Maldives do not need to apply for a visa pre-arrival, regardless of their country of origin, provided they have a valid passport, proof of onward travel, and the money to be self-sufficient while in the country. Most visitors arrive at Malé International Airport, on Hulhulé Island, adjacent to the capital Malé. The airport is served by flights to and from India, Sri Lanka, Doha, Dubai, Singapore, Istanbul, and major airports in South-East Asia, as well as charters from Europe. Gan Airport, on the southern atoll of Addu, also serves an international flight to Milan several times a week. British Airways offers direct flights to the Maldives around 2–3 times per week. The country currently has six heritage Maldivian coral mosques, all of which are listed as UNESCO tentative sites.', 'Maldives', 'Pesho', '', 1, 0),
(170, 'LOC_000548_shutterstock_1279328692WebOriginalCompressed.jpg', 'Pesho', '2019-07-05 22:59:42', '1', 'The Maldives archipelago is located on the Chagos-Laccadive Ridge, a vast submarine mountain range in the Indian Ocean, which also forms a terrestrial ecoregion, together with the Chagos Archipelago and Lakshadweep. Due to the consequent risks posed by rising sea levels, the government pledged in 2009 to make the Maldives a carbon-neutral country by 2019. The Maldives is a founding member of the South Asian Association for Regional Cooperation (SAARC). It is also a member of the United Nations, the Organization of Islamic Cooperation, and the Non-Aligned Movement. The World Bank classifies the Maldives as having an upper middle-income economy. Fishing has historically been the dominant economic activity, and remains the largest sector by far, followed by the rapidly growing tourism industry. Maldives is rated \"high\" on the Human Development Index, with its per capita income significantly higher than other SAARC nations. Visitors to the Maldives do not need to apply for a visa pre-arrival, regardless of their country of origin, provided they have a valid passport, proof of onward travel, and the money to be self-sufficient while in the country. Most visitors arrive at Malé International Airport, on Hulhulé Island, adjacent to the capital Malé. The airport is served by flights to and from India, Sri Lanka, Doha, Dubai, Singapore, Istanbul, and major airports in South-East Asia, as well as charters from Europe. Gan Airport, on the southern atoll of Addu, also serves an international flight to Milan several times a week. British Airways offers direct flights to the Maldives around 2–3 times per week. The country currently has six heritage Maldivian coral mosques, all of which are listed as UNESCO tentative sites.', 'Maldives', 'Pesho', '', 1, 0),
(172, '2018_02_01_39875_1517462499._large.jpg', 'Pesho', '2019-07-05 23:14:08', '1', 'Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species especially fish and turtles. In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean. Most recently, Bali was the host of the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site. It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation.', 'Bali', 'Pesho', '', 1, 0),
(173, 'Bali3.jpg', 'Pesho', '2019-07-05 23:14:08', '1', 'Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species especially fish and turtles. In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean. Most recently, Bali was the host of the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site. It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation.', 'Bali', 'Pesho', '', 1, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `photos`
--
ALTER TABLE `photos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `photos`
--
ALTER TABLE `photos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=185;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
